import random
n=random.randint(0,100)
# print(n)
count=0;
print("A random number is generated by the computer b\w 1 to 100..\nNow try to guess it baby..")

while(True):
    number=int(input())
    count=count+1
    if number>n:
        print("Nope!!Try a smaller number")
    elif number<n:
        print("Nope!!Try a bigger number")
    else:
        print("Correct!!You guessed it in ",count,"attempts")
        break

print("\nThank you for playing..You are a good sport..")

